version: '3.1'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: DockerfileNodeJs
    container_name: nodejs-app
    ports:
      - "5000:5000"
    networks:
      - example-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - example-network
  nginx:
    build:
      context: .
      dockerfile: DockerfileNginx
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
    networks:
      - example-network
    depends_on:
      - nodejs-app

networks:
  example-network:
    driver: bridge
    external: true